### ISSUE TITLE
All code for Obsedai 

### ISSUE THREAD

**Issue by RKiac** [HypatiaStation/Baystation12#27]
For: [Code\Modules\Admin\admins]

Line 152 <A href='?src=\ref[src];simplemake=human;species=Obsedai;mob=\ref[M]'>Obsedai</A>

For [code\modules\mob\living\carbon\human\species]
____________________________________________________________________________
Start on line 270:
/datum/species/obsedai
	name = "Obsedai"
	name_plural = "Obsedai"
	icobase = 'icons/mob/human_races/r_obsedai.dmi'
	language = "Tummese"
	unarmed_type = /datum/unarmed_attack/obsedai
	total_health = 500
	darksight = 8
	slowdown = 0.4
	brute_mod = 0.5

	cold_level_1 = -1 //Default 260
	cold_level_2 = -1 //Default 200
	cold_level_3 = -1 //Default 120

	heat_level_1 = 4000 //Default 360
	heat_level_2 = 5000 //Default 400
	heat_level_3 = 5500 //Default 1000

	primitive = /mob/living/carbon/monkey/tajara

	flags = IS_WHITELISTED | NO_SLIP | NO_BREATHE

	warning_low_pressure = 50
	hazard_low_pressure = -1

Under Species unarmed attacks:

Start on line: 563
/datum/unarmed_attack/obsedai
	attack_verb = list("smash", "bludgeon")
	damage = 40
	attack_sound = "punch"
	miss_sound = 'sound/weapons/punchmiss.ogg'
______________________________________________________________________

For [core\modules\mob\language]

Start on line 46:
/datum/language/obsedai
	name = "Tummese"
	desc = "The common tongue of the Obsedai. It sounds like deep rumbling and resonant notes to everyone else."
	speech_verb = "rumbles"
	ask_verb = "mumbles"
	exclaim_verb = "crashes"
	colour = "#008B8B"
	key = "9"
	native = 1
	flags = WHITELISTED

**Comment by TwistedAkai** [comment]
Evidently species have changed more than I thought since I last looked. This looks good overall, but the best way to submit code is to create a fork, edit the files on your side, and submit a pull request.

**Comment by RKiac** [comment]
Alright

**Comment by RKiac** [comment]
I'll be honest I'm staring at it and I have no idea what I'm supposed to be doing with it, I really can't figure out github

**Comment by RKiac** [comment]
Oh don't worry I was on an old version of the code, but I got this!

**Comment by RKiac** [comment]
Right none of this will work I've got the new code working and I've bug tested it But I'm going to need help getting it in I don't know how to fork.
